args<-commandArgs(TRUE)
library(Seurat)
library(dplyr)
rdsfilepath <- args[1]
print(rdsfilepath)
dat_2 <- readRDS(rdsfilepath)
dat_2 <-FindClusters(dat_2, resolution=0.5)
jpeg("TSNE_SNN.jpg", height = 1200, width = 1600)
DimPlot(dat_2)
dev.off()
All_Markers <- FindAllMarkers(dat_2, only.pos = TRUE, min.pct=0.25, logfc.threshold=0.25)
head(All_Markers)
write.table(All_Markers, file = "all_markers.csv", quote = FALSE, sep =",")
dat_2$cluster.idents <- Idents(object=dat_2)
Idents (object = dat_2) <- dat_2@meta.data$orig.ident
VST_Markers <- FindMarkers(dat_2, ident.1="VST", min.pct=0.25)
ATC_Markers <- FindMarkers(dat_2, ident.1="ATC", min.pct=0.25)
write.table(ATC_Markers, file = "ATC_markers.csv", quote = FALSE, sep =",")
write.table(VST_Markers, file = "VST_markers.csv", quote = FALSE, sep =",")
FeaturePlot(object=dat_2, features="CD8A", col=c("gray","darkblue"))
FeaturePlot(object=dat_2, features="CD4", col=c("gray","darkblue"))
head(FetchData(object=dat_2, vars= "CD4"))
range((FetchData(object=dat_2, vars= "CD4"))$CD4)
quantile((FetchData(object=dat_2, vars= "CD4"))$CD4)
saveRDS(dat_2, file="Seurat2.rds")
