### start of run
library(Seurat)
library(dplyr)
dat_1[["percent.mt"]] <- PercentageFeatureSet(dat_1, pattern ="^MT-", )
VlnPlot(dat_1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)
dev.off()
jpeg("QC_Violin.jpg")
VlnPlot(dat_1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),ncol=3)
dev.off()
Idents (object = dat_1) <- "All_cells"
plot1 <- FeatureScatter(dat_1, feature1="nCount_RNA", feature2="percent.mt")
plot2 <- FeatureScatter(dat_1, feature1="nCount_RNA", feature2="nFeature_RNA")
CombinePlots (plots=list(plot1,plot2))
dev.off()
jpeg("QC_plots.jpg", height = 1200, width = 1600)
CombinePlots (plots=list(plot1,plot2))
dev.off()
quantile(dat_1@meta.data$nFeature_RNA, prob=seq(0,1, length=41))
quantile(dat_1@meta.data$percent.mt, prob=seq(0,1, length=41))
dat_2 <-subset(dat_1, subset = nFeature_RNA >500 & nFeature_RNA < 5000 & percent.mt < 9.8)
length(dat_1@meta.data$percent.mt)
length(dat_2@meta.data$percent.mt)
# dat_1 has 18520 cells, dat_2 has 16089
dat_2 <- NormalizeData(dat_2)
dat_2 <- FindVariableFeatures(dat_2)
plot1 <- VariableFeaturePlot(dat_2)
top10 <- head(VariableFeatures(dat_2), 10)
plot2 <- LabelPoints(plot=plot1, points=top10, repel=TRUE)
#dev.off() ##Error in dev.off() : cannot shut down device 1 (the null device)
CombinePlots(plots=list(plot1,plot2))
jpeg("Highly_Var_genes.jpg")
CombinePlots(plots=list(plot1,plot2))
dev.off()
dat_2 <-ScaleData(dat_2)
dat_2 <-RunPCA(dat_2)
ElbowPlot(dat_2, ndims = 50)
dev.off()
jpeg("elbow_plot.jpg", height = 1200, width = 1600)
ElbowPlot(dat_2, ndims = 50)
dev.off()
dat_2 <-FindNeighbors(dat_2, dims = 1:30)
dat_2 <- RunTSNE(dat_2, dims=1:30, method="FIt-SNE")
DimPlot(dat_2)
Idents (object = dat_2) <- dat_2@meta.data$orig.ident
DimPlot(dat_2)
jpeg("Taka_TSNE.jpg", height = 1200, width = 1600)
DimPlot(dat_2)
dev.off()
dev.off()
#?FeaturePlot
FeaturePlot(object=dat_2, features="HER2CAR", col=c("gray","darkblue"))
jpeg("Taka_TSNE_HER2CAR.jpg", height = 1200, width = 1600)
FeaturePlot(object=dat_2, features="HER2CAR", col=c("gray","darkblue"))
dev.off()
saveRDS(dat_2, file="project-name.rds")
jpeg("highly_var_genes.jpg", height = 1200, width = 1600)
CombinePlots(plots=list(plot1,plot2))
dev.off()
#savehistory("20190923_seanVM.Rlog")
### This is end of QC and prelim analysis
